# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Score for negative binomial maximum-likelihood estimates
#' 
#' @param n Number of observations
#' @param th \eqn{\theta} parameter
#' @param mu Predicted values
#' @param y Observed values
#' 
#' @return Score value
score <- function(n, th, mu, y) {
    .Call('_gravity_score', PACKAGE = 'gravity', n, th, mu, y)
}

#' Information iteration value
#' 
#' @inheritParams score
info <- function(n, th, mu, y) {
    .Call('_gravity_info', PACKAGE = 'gravity', n, th, mu, y)
}

#' Maximum likelihood estimation for negative binomial models
#' 
#' Simplified C++ function for \link[MASS]{theta.ml}
#' 
#' @inheritParams MASS::theta.ml
#' @importFrom MASS theta.ml
#' 
#' @return A maximum-likelihood estimator for \eqn{\theta}
#' 
#' @seealso \link{fastglm.nb} ; \link[MASS]{theta.ml} ; \link[MASS]{glm.nb}
#' 
#' @references <Venables, W. N. and Ripley, B. D. (2002) Modern Applied Statistics with S. Fourth edition. Springer>
#' 
#' @export
#' 
speed_theta_ml <- function(y, mu, limit = 10L, eps = 1e-6, trace = TRUE) {
    .Call('_gravity_speed_theta_ml', PACKAGE = 'gravity', y, mu, limit, eps, trace)
}

